### ISSUE TITLE
Bug: distribution plots of lat, long, and ids

### ISSUE THREAD

**Issue by wikibag** [nesturie/Map_data_Bagboard#1]
Re 'Show Bar plot with Matlpotlib. 

Try to evaluate purpose of the plots you added. Why it is there and what you would like to emphasize?
Too many unrelated variables in one plot.
Plot title and axis legends missing

**Comment by nesturie** [comment]
The new files, that are uploaded, show the solution for the issues. 
*The data used in these files is not real data.
